# Generated by Django 5.2.16 on 2026-08-06 02:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'monitoring_machine',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='MachineReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('plc_online', models.BooleanField(default=False)),
                ('run_bit', models.BooleanField(default=False)),
                ('stop_bit', models.BooleanField(default=False)),
                ('alarm_bit', models.BooleanField(default=False)),
                ('auto_mode_bit', models.BooleanField(default=False)),
                ('production_count', models.BigIntegerField(default=0)),
                ('cycle_time_ms', models.IntegerField(blank=True, null=True)),
                ('alarm_code', models.IntegerField(default=0)),
                ('recipe_no', models.IntegerField(default=0)),
                ('source', models.CharField(choices=[('MOCK', 'Dữ liệu mô phỏng'), ('PLC', 'KEYENCE KV-8000')], default='MOCK', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readings', to='monitoring.machine')),
            ],
            options={
                'db_table': 'monitoring_machine_reading',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['machine', 'recorded_at'], name='mon_machine_time_idx')],
            },
        ),
    ]
