# Generated by Django 5.2.16 on 2026-08-12 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlcController',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('host', models.CharField(help_text='IPv4/hostname của PLC, ví dụ 192.168.0.10', max_length=255)),
                ('port', models.PositiveIntegerField(default=8501)),
                ('protocol', models.CharField(choices=[('KV_HOSTLINK_TCP', 'KEYENCE Host Link TCP')], default='KV_HOSTLINK_TCP', max_length=32)),
                ('poll_interval_ms', models.PositiveIntegerField(default=1000, help_text='Chu kỳ đọc PLC. Khuyến nghị 500-5000 ms.')),
                ('connect_timeout_ms', models.PositiveIntegerField(default=2000)),
                ('read_timeout_ms', models.PositiveIntegerField(default=2000)),
                ('history_interval_seconds', models.PositiveIntegerField(default=5, help_text='Dù collector poll nhanh hơn, một snapshot không đổi chỉ được lưu theo chu kỳ này để tránh phình database. Thay đổi trạng thái/giá trị được lưu ngay.')),
                ('offline_write_interval_seconds', models.PositiveIntegerField(default=10, help_text='Chu kỳ ghi heartbeat OFFLINE khi PLC mất kết nối.')),
                ('is_active', models.BooleanField(default=True)),
                ('last_poll_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'monitoring_plc_controller',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SignalMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal', models.CharField(choices=[('RUN', 'Máy chạy'), ('STOP', 'Máy dừng'), ('ALARM', 'Cảnh báo'), ('AUTO_MODE', 'Chế độ tự động'), ('PRODUCTION_COUNT', 'Sản lượng'), ('CYCLE_TIME_MS', 'Thời gian chu kỳ'), ('ALARM_CODE', 'Mã cảnh báo'), ('RECIPE_NO', 'Recipe / Product No.')], max_length=32)),
                ('address', models.CharField(help_text='Global device, ví dụ MR100 hoặc DM1000.', max_length=32)),
                ('data_type', models.CharField(choices=[('BIT', 'BIT'), ('UINT16', 'UINT16 (1 word unsigned)'), ('INT16', 'INT16 (1 word signed)'), ('UINT32', 'UINT32 (2 words unsigned)'), ('INT32', 'INT32 (2 words signed)')], default='UINT16', max_length=16)),
                ('word_order', models.CharField(choices=[('LOW_HIGH', 'Low word trước (DMn = low, DMn+1 = high)'), ('HIGH_LOW', 'High word trước (DMn = high, DMn+1 = low)')], default='LOW_HIGH', help_text='Chỉ dùng cho UINT32/INT32.', max_length=16)),
                ('scale', models.DecimalField(decimal_places=6, default=1, help_text='Giá trị web = raw × scale + offset.', max_digits=12)),
                ('offset', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'monitoring_signal_mapping',
                'ordering': ['machine__code', 'signal'],
            },
        ),
        migrations.AlterField(
            model_name='machinereading',
            name='source',
            field=models.CharField(choices=[('PLC', 'KEYENCE PLC')], default='PLC', max_length=10),
        ),
        migrations.AddIndex(
            model_name='machinereading',
            index=models.Index(fields=['machine', 'alarm_bit', 'recorded_at'], name='mon_machine_alarm_time_idx'),
        ),
        migrations.AddField(
            model_name='machine',
            name='controller',
            field=models.ForeignKey(blank=True, help_text='PLC vật lý đang chứa các device của máy này.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='monitoring.plccontroller'),
        ),
        migrations.AddField(
            model_name='signalmapping',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_mappings', to='monitoring.machine'),
        ),
        migrations.AddIndex(
            model_name='signalmapping',
            index=models.Index(fields=['machine', 'is_enabled'], name='mon_map_machine_enabled_idx'),
        ),
        migrations.AddConstraint(
            model_name='signalmapping',
            constraint=models.UniqueConstraint(fields=('machine', 'signal'), name='uniq_machine_signal_mapping'),
        ),
    ]
