# Generated by Django 5.2.16 on 2026-08-12 02:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_plccontroller_signalmapping_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineCurrentState',
            fields=[
                ('machine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='current_state', serialize=False, to='monitoring.machine')),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('plc_online', models.BooleanField(default=False)),
                ('run_bit', models.BooleanField(default=False)),
                ('stop_bit', models.BooleanField(default=False)),
                ('alarm_bit', models.BooleanField(default=False)),
                ('auto_mode_bit', models.BooleanField(default=False)),
                ('production_count', models.BigIntegerField(default=0)),
                ('cycle_time_ms', models.IntegerField(blank=True, null=True)),
                ('alarm_code', models.IntegerField(default=0)),
                ('recipe_no', models.IntegerField(default=0)),
                ('source', models.CharField(default='PLC', editable=False, max_length=10)),
                ('last_error', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'monitoring_machine_current_state',
                'ordering': ['machine__code'],
            },
        ),
        migrations.AlterField(
            model_name='plccontroller',
            name='connect_timeout_ms',
            field=models.PositiveIntegerField(default=2000, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(60000)]),
        ),
        migrations.AlterField(
            model_name='plccontroller',
            name='history_interval_seconds',
            field=models.PositiveIntegerField(default=30, help_text='Dù collector poll nhanh hơn, một snapshot không đổi chỉ được lưu theo chu kỳ này để tránh phình database. Trạng thái/alarm/recipe được lưu lịch sử ngay; giá trị số realtime nằm ở CurrentState.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(86400)]),
        ),
        migrations.AlterField(
            model_name='plccontroller',
            name='offline_write_interval_seconds',
            field=models.PositiveIntegerField(default=30, help_text='Chu kỳ ghi heartbeat OFFLINE khi PLC mất kết nối.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(86400)]),
        ),
        migrations.AlterField(
            model_name='plccontroller',
            name='poll_interval_ms',
            field=models.PositiveIntegerField(default=1000, help_text='Chu kỳ đọc PLC. Khuyến nghị 500-5000 ms.', validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(60000)]),
        ),
        migrations.AlterField(
            model_name='plccontroller',
            name='port',
            field=models.PositiveIntegerField(default=8501, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AlterField(
            model_name='plccontroller',
            name='read_timeout_ms',
            field=models.PositiveIntegerField(default=2000, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(60000)]),
        ),
    ]
